########################
### VARIABLES NEEDED ###
########################
# NPM_VERSION                   The version of npm to use when building (example: 6.14.5)
### Deploy
#
# DOCKER_REGISTRY           If true, then the packet will be published in a docker-registry
#                           ----------------- variables follow ----------------------------
# DEPLOYMENT_USER               User to use when SSHing to deployment server
# DEPLOYMENT_SERVER             Address of the deployment server to SSH to
# SSH_PORT                      Defaults to 22
# REGISTRY_URL                  Defaults to docker.io
# REGISTRY_USER                 The user of the registry to deploy to
# REGISTRY_PASSWORD             The password for the registry-user
# REGISTRY_PROJECT              Name of the project registered at your registry-provider
# REGISTRY_URL_AND_GROUP        The used URL will be: $REGISTRY_URL_AND_GROUP/$CI_PROJECT_NAME:latest
#                               So an example is 'gufalcon/nexus-server:latest'
# DEPLOYMENT_SSH_IV_VARNAME     When deploying over SSH, this will be the name of the CI-variable
# DEPLOYMENT_SSH_KEY_VARNAME    When deploying over SSH, this will be the name of the CI-variable
# SSH_ENC_FILE_NAME_WO_EXT      When deploying over SSH, this is the name of the encoded file
#                               without the extension
####################
### GENERAL INFO ###
####################
# - The 'deploy' step in Travis isn't the same process as the rest. So you have to re-source
#   the functions into that process. More than that it isn't a full sh process like with the
#   script-phase. So you cannot even source from there directly. That's why the source
#   command is IN the deploy.sh script.

language: node_js
node_js:
    - 14
cache:
    directories:
        - node_modules
before_install:
    - git clone https://github.com/UnterrainerInformatik/Travis-Scripts.git travis
    - source travis/functions.npm.sh
    - tr_setProjectSubdir npm
    - source $TRAVIS/before_install.sh
install:
    - source $TRAVIS/install.sh
before_script:
    - source $TRAVIS/before_script.sh
script:
    - source $TRAVIS/script.sh

before_deploy: ./$TRAVIS/before_deploy.sh
deploy:
    - provider: script
      skip_cleanup: true
      script: ./$TRAVIS/deploy.sh
      on:
          branch: master
    - provider: releases
      skip_cleanup: true
      overwrite: true
      api_key: $GITHUB_API_KEY
      file: $ARTIFACT_ID.$POM_VERSION.zip
      on:
          tags: true
          branch: master
