version: "3"
services:
  web:
    image: gufalcon/overmind-gui:latest
    restart: always
    ports:
      - "1880:80"
      - "18443:443"
    environment:
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
    volumes:
      - "/app/deploy/overmind-gui/nginx.conf:/etc/nginx/nginx.conf"
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - "traefik.enable=true"
      - "traefik.overmind.port=443"
      - "traefik.overmind.backend=overmind-gui"
      - "traefik.overmind.frontend.rule=Host:overmind.unterrainer.info"
      - "traefik.overmind.frontend.entryPoints=https"

networks:
  default:
    external:
      name: proxy_default
