version: "3"
services:
  web:
    image: gufalcon/overmind-gui:latest
    container_name: overmind-gui
    restart: always
    ports:
      - "1880:80"
      - "18443:443"
    environment:
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
    volumes:
      - "/app/deploy/overmind-gui/nginx.conf:/etc/nginx/nginx.conf"
      - "/app/deploy/cms-gui/config.js:/usr/share/nginx/html/config.js"
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.overmind-gui.rule=Host(`overmind.unterrainer.info`)
      - traefik.http.routers.overmind-gui.middlewares=std-headers@file,https-redirect@file
      - traefik.http.services.overmind-gui.loadbalancer.server.port=80

networks:
  default:
    external:
      name: proxy_default
